### ISSUE TITLE
任何关于考研的问题可以在此处提出

### ISSUE THREAD

**Issue by shercklo** [nju-kaoyan/nju_ai_20#1]

**Comment by Gowott** [comment]
请问20考研有人进LAMDA吗？

**Comment by shercklo** [comment]
有

**Comment by shercklo** [comment]
> 请问20考研有人进LAMDA吗？

有

**Comment by Nathanielll** [comment]
请问能不能帮忙联系下在wiki里写非全经验贴的学长，想考人工智能非全，有些问题想咨询，拜托了~~！

**Comment by ThyrixYang** [comment]
@Nathanielll 我觉得你加人工智能的群直接问比较好，你又不给你的联系方式我们怎么给你联系。。。

**Comment by MustForgiveHer** [comment]
> > 请问20考研有人进LAMDA吗？
> 
> 你好，20考研有进lamda组的，不好意思才看到你的问题

进AI院的是南大本校学生比较多还是外校更多？

**Comment by ThyrixYang** [comment]
@MustForgiveHer 外校的比本校多得多

**Comment by Fun007fun** [comment]
求问搜索不到群号怎么办

**Comment by ThyrixYang** [comment]
> 求问搜索不到群号怎么办

新群号，321376107

**Comment by Fun007fun** [comment]
> > 求问搜索不到群号怎么办
> 
> 新群号，321376107

谢谢你

**Comment by seven44** [comment]
确实是傻逼，操你妈，创建这个项目的死了全家了吧

**Comment by seven44** [comment]
有本事拉黑你爹，cnm

**Comment by Alafun** [comment]
> > 课程似乎已经进不去了, 不过有群友提前下载了下来：https://pan.baidu.com/s/12IrKc-PaX1Z7SeGnsUkh2g 提取码：zy7m

失效了
